"""initial schema

Revision ID: e41111bb8eb8
Revises: 
Create Date: 2026-03-30 13:15:15.804857

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e41111bb8eb8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('disaster',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=100), nullable=False),
    sa.Column('location', sa.String(length=100), nullable=False),
    sa.Column('severity', sa.String(length=50), nullable=True),
    sa.Column('priority', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('response_team', sa.String(length=120), nullable=True),
    sa.Column('date', sa.String(length=50), nullable=True),
    sa.Column('affected_display', sa.String(length=50), nullable=True),
    sa.Column('affected_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('password_initialized', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone'),
    sa.UniqueConstraint('username')
    )
    op.create_table('disaster_progress_update',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('disaster_id', sa.Integer(), nullable=False),
    sa.Column('message', sa.String(length=300), nullable=False),
    sa.Column('created_by', sa.String(length=80), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['disaster_id'], ['disaster.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('resource',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('location', sa.String(length=100), nullable=True),
    sa.Column('warehouse_info', sa.String(length=150), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('low_threshold', sa.Integer(), nullable=True),
    sa.Column('critical_threshold', sa.Integer(), nullable=True),
    sa.Column('disaster_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['disaster_id'], ['disaster.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('volunteer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('skills', sa.String(length=200), nullable=True),
    sa.Column('availability', sa.String(length=50), nullable=True),
    sa.Column('verification_status', sa.String(length=30), nullable=True),
    sa.Column('hours_logged', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('disaster_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['disaster_id'], ['disaster.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('volunteer_assignment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('volunteer_id', sa.Integer(), nullable=False),
    sa.Column('disaster_id', sa.Integer(), nullable=False),
    sa.Column('task_details', sa.String(length=250), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('hours_logged', sa.Integer(), nullable=True),
    sa.Column('assigned_by', sa.String(length=80), nullable=True),
    sa.Column('assigned_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['disaster_id'], ['disaster.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('volunteer_id', 'disaster_id', name='uix_volunteer_disaster')
    )
    op.create_table('activity_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=120), nullable=False),
    sa.Column('details', sa.String(length=300), nullable=True),
    sa.Column('actor_role', sa.String(length=30), nullable=True),
    sa.Column('actor_name', sa.String(length=80), nullable=True),
    sa.Column('disaster_id', sa.Integer(), nullable=True),
    sa.Column('resource_id', sa.Integer(), nullable=True),
    sa.Column('volunteer_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['disaster_id'], ['disaster.id'], ),
    sa.ForeignKeyConstraint(['resource_id'], ['resource.id'], ),
    sa.ForeignKeyConstraint(['volunteer_id'], ['volunteer.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('resource_allocation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('resource_id', sa.Integer(), nullable=False),
    sa.Column('disaster_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('notes', sa.String(length=250), nullable=True),
    sa.Column('allocated_by', sa.String(length=80), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['disaster_id'], ['disaster.id'], ),
    sa.ForeignKeyConstraint(['resource_id'], ['resource.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('resource_allocation')
    op.drop_table('activity_log')
    op.drop_table('volunteer_assignment')
    op.drop_table('volunteer')
    op.drop_table('resource')
    op.drop_table('disaster_progress_update')
    op.drop_table('user')
    op.drop_table('disaster')
    # ### end Alembic commands ###
